#! /bin/python

python /home/tooba/MetaXcan/software/SPrediXcan.py \
--model_db_path /home/wheelerlab3/Data/predictdb_models/scPrediXcan_models/l-ctPred_models_for_immune_cell_types_from_OneK1K_dataset/CD14-low_CD16-positive_monocyte.db \
--covariance /home/wheelerlab3/Data/predictdb_models/scPrediXcan_models/l-ctPred_models_for_immune_cell_types_from_OneK1K_dataset/CD14-low_CD16-positive_monocyte_covariances.txt.gz \
--gwas_file /home/tooba/hg38_SPx_format_GCST90479798.h.tsv \
--snp_column panel_variant_id \
--chromosome_column chromosome \
--or_column odds_ratio \
--effect_allele_column effect_allele \
--non_effect_allele_column non_effect_allele \
--pvalue_column pvalue \
--beta_column effect_size \
--keep_non_rsid \
--model_db_snp_key varID \
--output_file GCST90479798_predixcan_output_immune_CD14-low_CD16-positive_monocyte.demo11.csv

